# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "zh-CN"

reviews:
  request_changes_workflow: true
  high_level_summary_placeholder: "[[SUMMARY]]"
  auto_title_placeholder: "[[TITLE]]"
  poem: false