site_name: mhyy.py

# Theme
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path

# Repository
repo_name: Mooneze/mhyy.py
repo_url: https://github.com/Mooneze/mhyy.py

# Navigation
nav:
  - 简介: index.md
  - 使用:
      - 快速入门: usage/quick_start.md
      - 多客户端支持: usage/multi_client_support.md
  - 附录:
      - 获取你的 Headers: appendix/get_headers.md
  - API 参考:
      - 开发人员接口: api/interface.md

# Plugin
plugins:
  - tags

# noinspection YAMLSchemaValidation
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences