name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          
      - name: Build package
        run: python -m build

      - name: Get package
        run: |
          echo find ./dist/ -name *.whl
          echo "package=$(find ./dist/ -name *.whl)" >> "$GITHUB_ENV"

      - name: Release package
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
          name: mhyy.py ${{ github.ref_name }}
          files: ${{ env.package }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}