name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag (v3.x.x)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          
      - name: Build package
        run: python -m build

      - name: Get package
        run: |
          find ./dist/ -name *.whl
          echo "package=$(find ./dist/ -name *.whl)" >> "$GITHUB_ENV"

      - name: Release package
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          name: mhyy.py ${{ inputs.release-tag }}
          tag_name: ${{ inputs.release-tag }}
          files: ${{ env.package }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}